spring:
  profiles: default
datasource:
  master:
      driver-class-name: "com.mysql.jdbc.Driver"
      url: "jdbc:mysql://localhost:3306/instalove?useUnicode=true&charaterEncoding=utf-8"
      user-name: "guest"
      password: "1234"
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000
  slave:
      driver-class-name: "com.mysql.jdbc.Driver"
      url: "jdbc:mysql://localhost:3306/instalove?useUnicode=true&charaterEncoding=utf-8"
      user-name: "guest"
      password: "1234"
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
      max-wait: 3000
